[server]
port = 8502
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor="#3d85c6"
backgroundColor="#0e1117"
secondaryBackgroundColor="#1e2329"
textColor="#fafafa"
font="sans serif"
